const sampleAssets = [
    {
        "assetName": "Gap Sub",
        "assetType": "Asset",
        "deployedLocation": "Rig ABC",
        "owner": "Evolution-USA",
        "parentId": "G8001119",
        "lastUpdated": null,
        "serial": "G8001111",
        "checkedOut": true,
        "groupTag": "",
        "assignmentType": "Rental",
        "assignee": "Nabors Drilling",
        "contractNumber": "202012345",
        "retired": false,
    },
    {
        "assetName": "Centralizer",
        "assetType": "Asset",
        "deployedLocation": "Rig ABC",
        "owner": "Evolution-USA",
        "parentId": "G8001119",
        "serial": "C8001011",
        "checkedOut": true,
        "groupTag": "",
        "assignmentType": "Owned",
        "assignee": "Nabors Drilling",
        "contractNumber": "202015",
        "retired": false,
    },
    {
        "assetType": "Asset",
        "assetName": "Crossover Sub",
        "deployedLocation": "",
        "owner": "Evolution-USA",
        "parentId": "G8001119",
        "serial": "X800920",
        "checkedOut": false,
        "groupTag": "",
        "assignmentType": "Owned",
        "assignee": "",
        "contractNumber": "",
        "retired": true,
    },
    {
        "assetType": "Assembly",
        "assetName": "Carrier",
        "deployedLocation": "",
        "owner": "Evolution-USA",
        "parentId": null,
        "serial": "G8001119",
        "checkedOut": false,
        "groupTag": "",
        "assignmentType": "Owned",
        "assignee": "",
        "contractNumber": "",
        "retired": true,
    }
];

module.exports = sampleAssets;